config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  root 'static_pages#index'

  resources :merits, only: [] do
    get :new, on: :member
    post :create, on: :member
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/merit.rb
class Merit < ActiveRecord::Base
  belongs_to :meritor, class_name: "User"
  belongs_to :meritee, class_name: "User"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to  :organization
  has_many    :given_merits,    class_name: "Merit", foreign_key: "meritor_id"
  has_many    :received_merits, class_name: "Merit", foreign_key: "meritee_id"

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

  def require_login
    unless session[:user_id].present? && @user = User.find_by(id: session[:user_id])
      redirect_to new_session_path
    end
  end
end

app/controllers/merits_controller.rb
class MeritsController < ApplicationController
  before_action :require_login

  def new
    @merit = Merit.new
    @meritee = User.find_by(id: params[:id])
  end

  def create
    @meritee = User.find_by(id: params[:id])
    return redirect_with_error("invalid parameters") unless @meritee.present? && @meritee.organization.id == @user.organization.id

    weeks_merits = @user.given_merits.where("created_at > ?", Time.zone.now.beginning_of_week)
    return redirect_with_error("You have already used your kudos for the week") unless weeks_merits.length < 3

    weeks_merits.each do |wm|
      return redirect_with_error("You already gave #{@meritee.name} kudos this week") if wm.meritee.id == @meritee.id
    end

    @merit = @user.given_merits.new(merit_params)
    @merit.meritee_id = @meritee.id
    if @merit.save
      flash[:success] = "you gave kudos to #{@meritee.name}"
      redirect_to users_show_path
    else
      render "new"
    end

  end

  private

  def redirect_with_error(message)
    flash[:error] = message
    redirect_to users_show_path
  end

  def merit_params
    params.require(:merit).permit(:message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user.present? && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to users_show_path
    else
      flash.now[:error] = 'Invalid credentials'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @organizations = Organization.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show

    weeks_merits = @user.given_merits.where("created_at > ?", Time.zone.now.beginning_of_week)
    team = @user.organization.try(:users) || []

    @weeks_merit_count = weeks_merits.length
    @meritees = []
    @candidates = []

    #divide members of organization into two arrays:
    #Those who have been given Kudos and those who have not.
    team.each do |team_mate|
      unless team_mate.id == @user.id
        already_recipient = false
        weeks_merits.each do |wm|
          already_recipient = true if wm.meritee_id == team_mate.id
        end
        if already_recipient
          @meritees.push team_mate
        else
          @candidates.push team_mate
        end
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    session[:user_id].present? && User.find_by(id: session[:user_id])
  end
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{ :charset => "utf-8" }
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge" }
    %title "Kudos"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', :async => Rails.env.production?
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        %ul.nav.navbar-nav
          %li.active
            = link_to "home", root_path
          - if signed_in?
            %li.active
              = link_to "Profile", users_show_path
            %li.active
              = link_to "Sign Out", sessions_path, method: "delete"
          - else
            %li.active
              = link_to "Sign In", new_session_path
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}") 
      = yield

app/views/merits/new.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h3.ta-center Give Kudos to #{@meritee.name}

    = form_for @merit, url: merit_path(@meritee) do |f|
      = f.label :message
      = f.text_area :message, class: "form-control"

      = f.submit "Give Kudos", class: "btn btn-large btn-primary"
      

app/views/static_pages/index.html.haml
%h1 Kudos

- @organizations.each do |org|
  %h3= org.name
  -org.users.each do |user|
    %h5= user.email

app/views/users/show.html.haml
.row
  .col-xs-12
    %h6 organization: #{@user.organization.try(:name)}
    %h6 name: #{@user.name}
    %h6 email: #{@user.email}
.row
  .col-xs-6
    -if @weeks_merit_count < 3
      %h3.ta-center Give Kudos
      -@candidates.each do |meritee|
        .give-merit
          %h5
            %a
              = link_to merit_path(meritee), class: "btn btn-default" do
                %i.glyphicon.glyphicon-thumbs-up
                = meritee.name
    %h3.ta-center Kudos Already Given
    -@meritees.each do |meritee|
      .give-merit
        %h5 #{meritee.name}
  .col-xs-6
    %h3.ta-center Kudos Received
    -@user.received_merits.order(created_at: :desc).each do |merit|
      .merit-display
        %p.merit-message
          = merit.message
        %h5.pull-right= merit.meritor.name
        %h5.pull-right.clear= merit.created_at.strftime("%b %e, %Y")
        .clear